spring:
  datasource:
    url: jdbc:mysql://101.126.86.48:3306/sencondhand_market
    username: root
    password: nyg4!65k
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 101.126.86.48
    port: 6379
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


app:
  jwt:
    secret: "yhzhu"
    expireMinutes: 120
  uploadDir: uploads
  tos:
    endpoint: "tos-cn-beijing.volces.com"  # TOS endpoint
    region: "cn-beijing"  # TOS region，格式：cn-beijing（不是完整endpoint）
    accessKey:  ${VOLC_ACCESS_KEY_ID}
    secretKey:  ${VOLC_ACCESS_KEY_SECRET}
    bucketName: "work2"


server:
  port: 8080



